services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    environment:
      - PUBLIC_ANON_KEY=${PUBLIC_ANON_KEY}
      - PUBLIC_SUPABASE_URL=${PUBLIC_SUPABASE_URL}
    depends_on:
      - backend
    network_mode: "host"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '3080:3080'
    volumes:
      - ./output:/app/output
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    network_mode: "host"

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    network_mode: "host"
