services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    env_file:
      - frontend/.env.local
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '3080:3080'
    volumes:
      - ./output:/app/output
    environment:
      DATABASE_URL: ''
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
